### ISSUE TITLE
Push to Maven Central

### ISSUE THREAD

**Issue by hhfrancois** [hhdevelopment/ocelot#1]
trouver comment on publie sur maven central

http://maven.apache.org/guides/mini/guide-central-repository-upload.html

**Comment by nainpo** [comment]
C'est la page sur laquelle je suis tombé avant de voir ton issue.

Il y a pas mal de requirements, parmis lesquels on trouve: 
- Fournir les sources et la javadoc
- Signer les files publised avec une clé gpg/pgp (l'explication fournise est claire)
- La metadata habituelle, groupid, artifactid, version, project name, description, url...
- Notre license ? Voir les licenses open source existantes (<licenses />)
- Les informations des développeurs (<developpers />)
- Les informations pour se connecter a notre repo git (<scm />)

La liste, explications et un exemple de pom complet se trouve sur cette page http://central.sonatype.org/pages/requirements.html

**Comment by hhfrancois** [comment]
Bon, les sources et javadoc, ca ca devrait aller.
signer, par contre c'est a dire, comment ?
les metas, je penses que c'est bon...
une licence, faudra en chosir une.
Info dév, ok, comment sous quel format
Les info pour git, c'est à dire, c'est public

**Comment by hhfrancois** [comment]
pour les infos dev, donne moi les infos que tu veux qui figure dans le pom, nom prenom, email

**Comment by hhfrancois** [comment]
pour la licence MPL 2.0 
https://www.mozilla.org/MPL/2.0/
C'est libre de réutiliser même pour du non open, mais les auteurs doivent être citée

**Comment by hhfrancois** [comment]
http://maven.apache.org/maven-release/maven-release-plugin/index.html
plugin à considérer

**Comment by nainpo** [comment]
Pour la signature c'est ces fichiers là qu'il va falloir signer : 

> Sign Files with GPG/PGP
> All files deployed need to be signed with GPG/PGP and a .asc file containing the signature must be included for each file. E.g. if you deploy the files
> 
> example-application-1.4.7.pom
> example-application-1.4.7.jar
> example-application-1.4.7-sources.jar
> example-application-1.4.7-javadoc.jar
> 
> you need to include the files ->
> 
> example-application-1.4.7.pom.asc
> example-application-1.4.7.jar.asc
> example-application-1.4.7-sources.jar.asc
> example-application-1.4.7-javadoc.jar.asc

Pour signer les files, il va falloir suivre les explications sur ce lien : http://central.sonatype.org/pages/working-with-pgp-signatures.html elles sont assez claires

**Comment by nainpo** [comment]
Pour les developpeurs c'est une simple balise a placer dans le pom 

``` xml
<developers>
    <developer>
      <name>Manfred Moser</name>
      <email>manfred@sonatype.com</email>
      <organization>Sonatype</organization>
      <organizationUrl>http://www.sonatype.com</organizationUrl>
    </developer>
  </developers>
```

Tout comme la license : 

``` xml
<licenses>
  <license>
    <name>The Apache License, Version 2.0</name>
    <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
  </license>
</licenses>
```

Et les infos du SCM : 

``` xml
<scm>
  <connection>scm:git:git@github.com:juven/git-demo.git</connection>
  <developerConnection>scm:git:git@github.com:juven/git-demo.git</developerConnection>
  <url>git@github.com:juven/git-demo.git</url>
</scm>
```

**Comment by nainpo** [comment]
Tu as une addresse mail pour dev ? Je devrais m'en faire une pour l'occasion :e-mail:

**Comment by hhfrancois** [comment]
j'ai créer une demande dans OSS Sonatype, pourles projet opensource, ils héberge les artifact et propose un JIRA (si j'ai bien compris)
https://issues.sonatype.org/browse/OSSRH-15324
Créez un compte dessus quandle projet sera bon, on utilisera ca encas
