### ISSUE TITLE
https and wss over ws

### ISSUE THREAD

**Issue by pierre-guillot-gh** [hhdevelopment/ocelot#38]
When testing ocelot in https environnement, i got this error :

Mixed Content: The page at 'https://yourdomain.com' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://https://yourdomain.com/ocelot-endpoint'. This request has been blocked; this endpoint must be available over WSS.init @ ocelot.js:1(anonymous function) @ ocelot.js:1(anonymous function) @ ocelot.js:1

How to tell ocelot to use wss over ws ?

**Comment by hhfrancois** [comment]
protocol is automaticly detected.
use https set wss
use http set ws
