### ISSUE TITLE
add a security check on JsTopics before publishing a message to suscribers

### ISSUE THREAD

**Issue by devauxbr** [hhdevelopment/ocelot#44]
It would be great if we could create our own EJB implementing the relevant interface : for a specific topic, it would check if a new published message can be sent to each the suscriber

**Comment by hhfrancois** [comment]
For the 2.9.1 I propose something like that :
implement JsTopicMessageController annotated JsTopicControl(TOPICNAME)
You will have to implement method checkRight

``` java
@JsTopicControl("MYTOPIC")
public class MyJsTopicMessageController implements JsTopicMessageController {
   public void checkRight(UserContext ctx, MessageToClient mtc) throws NotRecipientException {
       ...
   }
}
public interface UserContext {
   Principal getPrincipal();
   boolean isUserInRole(String role);
}
```

You cannot use SessionContext, cause the sessionContext come from User send message not recipient. So I build a UserContext that expose username and a method for check roles.
But I guess some problems,
- the MessageToClient should not be modified, but you access it
- the MessageToClient bears the response, but
  1. the response is a java object, so it can bears informations for check if the user can be receive it
  2. the response is already in json format, less easy to test it.!!!
     so, maybe I can add informations like key/value on messageToClient
     Like this the message bears  additional informations for compute rights about it.
     But in most of case, you don't build the MessageToClient, just fire a payload... so it's not possible in this case to add information on messageToClient.

What do you think about that ?
